from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


AgentStatus = Literal[
    "running",
    "needs_input",
    "plan_ready",
    "accepted",
]


class ResearchResult(BaseModel):
    """A single web snippet used as evidence for architecture decisions."""

    title: str = ""
    snippet: str = ""
    link: str = ""
    query: str = ""
    source_domain: str = ""
    is_official_source: bool = False


class QuestionOption(BaseModel):
    """A single option for a clarifying question."""

    label: str = ""
    value: str = ""
    is_custom: bool = False


class QuestionWithOptions(BaseModel):
    """A clarifying question with predefined options and a custom input option."""

    question: str = ""
    options: list[QuestionOption] = Field(default_factory=list)
    original_question: str = ""  # The underlying follow-up question for fallback


class ClarifierOutput(BaseModel):
    """Structured clarifier response to avoid ad-hoc JSON parsing logic."""

    is_information_enough: bool = False
    follow_up_questions: list[str] = Field(default_factory=list)
    questions_with_options: list[QuestionWithOptions] = Field(default_factory=list)
    research_queries: list[str] = Field(default_factory=list)


class FinalPRDJson(BaseModel):
    """Final PRD-like structure consumed by downstream service selection logic."""

    model_config = ConfigDict(extra="ignore")

    scope: str = ""
    product_summary: str = ""
    functional_requirements: list[str] = Field(default_factory=list)
    non_functional_requirements: list[str] = Field(default_factory=list)
    proposed_cloud_services: list[str] = Field(default_factory=list)
    architecture_decisions: list[str] = Field(default_factory=list)
    deployment_plan: list[str] = Field(default_factory=list)
    risks_and_mitigations: list[str] = Field(default_factory=list)
    assumptions: list[str] = Field(default_factory=list)
    open_questions: list[str] = Field(default_factory=list)
    references: list[str] = Field(default_factory=list)


class PlannerOutput(BaseModel):
    """Top-level planner output with markdown plus machine-readable PRD JSON."""

    model_config = ConfigDict(extra="ignore")

    plan_markdown: str
    plan_json: FinalPRDJson


class AgentState(BaseModel):
    """LangGraph state model validated on each step and API boundary."""

    model_config = ConfigDict(extra="ignore", validate_assignment=True)

    # Unique conversation/session identifier used to resume loops across calls.
    session_id: str | None = None
    # Cloud target used to choose trusted documentation domains and service vocabulary.
    cloud_provider: str = "aws"
    # Initial natural-language user request for the product.
    prd_text: str = ""
    # Accumulated natural-language clarifications supplied by the user.
    user_answers: list[str] = Field(default_factory=list)
    # Follow-up questions generated by the clarifier node.
    follow_up_questions: list[str] = Field(default_factory=list)
    # Questions with multiple-choice options for enhanced user interaction.
    questions_with_options: list[QuestionWithOptions] = Field(default_factory=list)
    # User-selected answers mapped by question index or question text.
    selected_option_answers: dict[int, str] = Field(default_factory=dict)
    # Query plan used by research node to fetch official cloud docs.
    research_queries: list[str] = Field(default_factory=list)
    # Evidence snippets retained for grounded planning.
    research_results: list[ResearchResult] = Field(default_factory=list)
    # Gate flag deciding whether we can proceed to final PRD generation.
    is_information_enough: bool = False
    # Human-readable plan/PRD narrative.
    plan_markdown: str | None = None
    # Machine-readable PRD object validated with Pydantic.
    plan_json: FinalPRDJson | None = None
    # Optional user feedback from plan rejection cycles.
    acceptance_feedback: str = ""
    # Explicit user decision on the produced PRD.
    accepted: bool | None = None
    # Current graph status for API clients and control flow.
    status: AgentStatus = "running"
    # Non-fatal execution issues captured for observability.
    errors: list[str] = Field(default_factory=list)
    # Number of clarification rounds completed so far.
    clarification_rounds: int = 0
    # Internal flag to trigger web-search node.
    run_web_search: bool = False
    # Internal flag indicating web-search node already executed.
    web_search_done: bool = False

    def add_error(self, message: str) -> None:
        self.errors.append(message)

    def as_graph_state(self) -> dict[str, Any]:
        return self.model_dump(mode="json")
