'use client';

import { motion } from 'framer-motion';
import { Zap, Globe, Database } from 'lucide-react';

const EASE = [0.16, 1, 0.3, 1] as const;

const HCL = `# Generated by Claude Sonnet 3.5 · 2.3s
# CloudForge topology: api-handler → rest-api → postgres-db

variable "db_password" {
  description = "RDS master password"
  type        = string
  sensitive   = true
}

provider "aws" {
  region = "us-east-1"
}

resource "aws_iam_role" "lambda_exec" {
  name = "cloudforge-lambda-exec"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action    = "sts:AssumeRole"
      Effect    = "Allow"
      Principal = { Service = "lambda.amazonaws.com" }
    }]
  })
}

resource "aws_iam_role_policy_attachment" "lambda_basic" {
  role       = aws_iam_role.lambda_exec.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

resource "aws_lambda_function" "api_handler" {
  function_name = "cloudforge-api-handler"
  runtime       = "nodejs20.x"
  handler       = "index.handler"
  role          = aws_iam_role.lambda_exec.arn
  filename      = "lambda.zip"

  environment {
    variables = {
      DB_HOST = aws_db_instance.postgres.endpoint
    }
  }

  depends_on = [aws_iam_role_policy_attachment.lambda_basic]
}

resource "aws_lambda_permission" "apigw_invoke" {
  statement_id  = "AllowAPIGatewayInvoke"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.api_handler.function_name
  principal     = "apigateway.amazonaws.com"
  source_arn    = "\${aws_api_gateway_rest_api.main.execution_arn}/*/*"
}

resource "aws_api_gateway_rest_api" "main" {
  name        = "cloudforge-api"
  description = "Generated by CloudForge"
}

resource "aws_db_instance" "postgres" {
  identifier          = "cloudforge-db"
  engine              = "postgres"
  engine_version      = "15.4"
  instance_class      = "db.t3.micro"
  allocated_storage   = 20
  username            = "admin"
  password            = var.db_password
  skip_final_snapshot = true
}`;

function highlight(code: string): string {
  return code
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(
      /\b(provider|resource|variable|output|locals|module|data|terraform)\b/g,
      '<span style="color:#6EAB85;font-weight:500">$1</span>'
    )
    .replace(
      /"([^"]+)"/g,
      '<span style="color:#A3C9B4">"$1"</span>'
    )
    .replace(
      /\b(true|false|null)\b/g,
      '<span style="color:#9CA3AF">$1</span>'
    )
    .replace(
      /(#[^\n]*)/g,
      '<span style="color:#4B5563">$1</span>'
    );
}

const MINI_NODES = [
  { label: 'api-handler', subtitle: 'Lambda · nodejs20.x', dotColor: '#00ff87', iconColor: '#FF9900', Icon: Zap },
  { label: 'rest-api', subtitle: 'API Gateway · REST', dotColor: '#00d4ff', iconColor: '#FF4F8B', Icon: Globe },
  { label: 'postgres-db', subtitle: 'RDS · postgres 15', dotColor: '#00d4ff', iconColor: '#527FFF', Icon: Database },
];

export default function TerraformPreview() {
  return (
    <section
      style={{
        padding: '120px 24px',
        maxWidth: '1100px',
        margin: '0 auto',
      }}
    >
      {/* Section header */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true, margin: '-80px' }}
        transition={{ duration: 0.6, ease: EASE }}
        style={{ marginBottom: '56px' }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '20px' }}>
          <div style={{ height: '1px', width: '32px', background: 'var(--lp-accent)', opacity: 0.6 }} />
          <span
            style={{
              fontFamily: 'var(--font-inter), system-ui, sans-serif',
              fontSize: '11px',
              letterSpacing: '0.12em',
              textTransform: 'uppercase' as const,
              color: 'var(--lp-text-hint)',
            }}
          >
            What CloudForge generates
          </span>
        </div>
        <h2
          style={{
            fontFamily: 'var(--font-inter), system-ui, sans-serif',
            fontSize: 'clamp(28px, 3.5vw, 42px)',
            fontWeight: 600,
            color: 'var(--lp-text-primary)',
            letterSpacing: '-0.03em',
            lineHeight: 1.1,
            maxWidth: '520px',
          }}
        >
          Draw a diagram.{' '}
          <span style={{ color: 'var(--lp-text-secondary)', fontWeight: 400 }}>
            Get production Terraform.
          </span>
        </h2>
      </motion.div>

      {/* Split layout */}
      <div
        style={{
          display: 'grid',
          gridTemplateColumns: '1fr 1.5fr',
          gap: '2px',
          background: 'var(--lp-border)',
          borderRadius: '16px',
          overflow: 'hidden',
          border: '1px solid var(--lp-border)',
        }}
      >
        {/* Left: mini canvas */}
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true, margin: '-60px' }}
          transition={{ duration: 0.7, ease: EASE }}
          style={{
            background: 'var(--lp-bg)',
            padding: '32px 24px',
            display: 'flex',
            flexDirection: 'column',
            gap: '8px',
            justifyContent: 'center',
          }}
        >
          <div
            style={{
              fontFamily: 'var(--font-jetbrains-mono), monospace',
              fontSize: '10px',
              color: 'var(--lp-text-hint)',
              marginBottom: '16px',
              letterSpacing: '0.05em',
            }}
          >
            // your diagram
          </div>
          {MINI_NODES.map((node, i) => {
            const Icon = node.Icon;
            return (
              <div
                key={node.label}
                style={{
                  background: '#12172b',
                  border: '0.5px solid rgba(255,255,255,0.08)',
                  borderRadius: '10px',
                  padding: '10px 12px',
                  marginLeft: i === 0 ? 0 : '24px',
                }}
              >
                <div style={{ display: 'flex', alignItems: 'center', gap: '7px', marginBottom: '3px' }}>
                  <div
                    style={{ width: '7px', height: '7px', borderRadius: '50%', background: node.dotColor, flexShrink: 0 }}
                  />
                  <Icon size={12} style={{ color: node.iconColor, flexShrink: 0 }} />
                  <span
                    style={{
                      fontFamily: 'var(--font-inter), system-ui, sans-serif',
                      fontSize: '12px',
                      fontWeight: 500,
                      color: '#cdd6f4',
                    }}
                  >
                    {node.label}
                  </span>
                </div>
                <div
                  style={{
                    fontFamily: 'var(--font-jetbrains-mono), monospace',
                    fontSize: '9px',
                    color: '#6c7086',
                    paddingLeft: '14px',
                  }}
                >
                  {node.subtitle}
                </div>
              </div>
            );
          })}
          <div
            style={{
              marginTop: '16px',
              display: 'flex',
              alignItems: 'center',
              gap: '6px',
            }}
          >
            <div style={{ width: '5px', height: '5px', borderRadius: '50%', background: 'var(--lp-accent)' }} />
            <span
              style={{
                fontFamily: 'var(--font-jetbrains-mono), monospace',
                fontSize: '10px',
                color: 'var(--lp-accent)',
                letterSpacing: '0.02em',
              }}
            >
              claude sonnet 3.5 → generating hcl...
            </span>
          </div>
        </motion.div>

        {/* Right: HCL output */}
        <motion.div
          initial={{ opacity: 0, x: 20 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true, margin: '-60px' }}
          transition={{ duration: 0.7, ease: EASE, delay: 0.1 }}
          style={{
            background: '#0D0F13',
            padding: '0',
            overflow: 'hidden',
          }}
        >
          {/* File tab */}
          <div
            style={{
              padding: '10px 20px',
              borderBottom: '1px solid var(--lp-border)',
              display: 'flex',
              alignItems: 'center',
              gap: '8px',
            }}
          >
            <div style={{ width: '8px', height: '8px', borderRadius: '2px', background: 'rgba(110,171,133,0.4)' }} />
            <span
              style={{
                fontFamily: 'var(--font-jetbrains-mono), monospace',
                fontSize: '11px',
                color: 'var(--lp-text-secondary)',
              }}
            >
              main.tf
            </span>
            <span
              style={{
                marginLeft: 'auto',
                fontFamily: 'var(--font-jetbrains-mono), monospace',
                fontSize: '10px',
                color: 'var(--lp-text-hint)',
              }}
            >
              Generated by Claude Sonnet 3.5 · 2.3s
            </span>
          </div>
          {/* Code */}
          <pre
            style={{
              fontFamily: 'var(--font-jetbrains-mono), monospace',
              fontSize: '11.5px',
              lineHeight: 1.75,
              color: 'var(--lp-text-secondary)',
              padding: '20px',
              margin: 0,
              overflowX: 'auto',
              maxHeight: '380px',
              overflowY: 'auto',
            }}
            dangerouslySetInnerHTML={{ __html: highlight(HCL) }}
          />
        </motion.div>
      </div>
    </section>
  );
}
